# Generated by Django 5.0.1 on 2024-02-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_marketing",
            field=models.FloatField(verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_marketing_promotional",
            field=models.FloatField(default=0, verbose_name="Promotional"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("V", "Variable"), ("S", "Simple")], default="V", max_length=1
            ),
        ),
    ]
