# Generated by Django 5.0.1 on 2024-02-10 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="cpf",
            new_name="ssn",
        ),
    ]
